# Generated by Django 4.0.7 on 2022-09-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_album_owner_photo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='data',
            field=models.TextField(blank=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
